version: '3.8'

services:
  # La base de données
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # L'outil d'automatisation pour tes agents IA
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      -  N8N_HOST=localhost 
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Paris
      # ✅ Autoriser CORS pour le frontend
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_CORS_ENABLED=true
      - N8N_CORS_ALLOW_ORIGIN=*
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  mongo_data:
  n8n_data: