/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    messages: Message;
    bourses: Bourse;
    candidatures: Candidature;
    entretiens: Entretien;
    favoris: Favoris;
    roadmap: Roadmap;
    feedbacks: Feedback;
    match: Match;
    recommendations: Recommendation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    bourses: BoursesSelect<false> | BoursesSelect<true>;
    candidatures: CandidaturesSelect<false> | CandidaturesSelect<true>;
    entretiens: EntretiensSelect<false> | EntretiensSelect<true>;
    favoris: FavorisSelect<false> | FavorisSelect<true>;
    roadmap: RoadmapSelect<false> | RoadmapSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    match: MatchSelect<false> | MatchSelect<true>;
    recommendations: RecommendationsSelect<false> | RecommendationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  pays?: string | null;
  niveau?: string | null;
  domaine?: string | null;
  phone?: string | null;
  nationality?: string | null;
  countryOfResidence?: string | null;
  linkedin?: string | null;
  github?: string | null;
  portfolio?: string | null;
  currentLevel?: string | null;
  fieldOfStudy?: string | null;
  institution?: string | null;
  gpa?: string | null;
  graduationYear?: string | null;
  targetDegree?: string | null;
  motivationSummary?: string | null;
  academicHistory?:
    | {
        degree?: string | null;
        institution?: string | null;
        field?: string | null;
        year?: string | null;
        grade?: string | null;
        id?: string | null;
      }[]
    | null;
  workExperience?:
    | {
        type?: string | null;
        position?: string | null;
        company?: string | null;
        city?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        technologies?: string | null;
        id?: string | null;
      }[]
    | null;
  academicProjects?:
    | {
        title?: string | null;
        type?: string | null;
        supervisor?: string | null;
        year?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        technologies?: string | null;
        link?: string | null;
        teamSize?: string | null;
        impact?: string | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name?: string | null;
        issuer?: string | null;
        date?: string | null;
        credential?: string | null;
        id?: string | null;
      }[]
    | null;
  volunteerWork?:
    | {
        role?: string | null;
        organization?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  publications?:
    | {
        title?: string | null;
        venue?: string | null;
        year?: string | null;
        authors?: string | null;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        title?: string | null;
        organization?: string | null;
        year?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language?: string | null;
        level?: string | null;
        certificate?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        skill?: string | null;
        level?: string | null;
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  targetCountries?:
    | {
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  targetFields?:
    | {
        field?: string | null;
        id?: string | null;
      }[]
    | null;
  progression?:
    | {
        bourseNom?: string | null;
        etape?: number | null;
        updatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  magicToken?: string | null;
  magicTokenExpiration?: string | null;
  bourses_choisies?:
    | {
        nom: string;
        pays?: string | null;
        url?: string | null;
        deadline?: string | null;
        langue?: string | null;
        ajouteLe?: string | null;
        id?: string | null;
      }[]
    | null;
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  text: string;
  role: 'user' | 'assistant';
  conversationId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bourses".
 */
export interface Bourse {
  id: string;
  nom: string;
  pays: string;
  /**
   * Domaines d'études couverts par la bourse (rempli automatiquement par le workflow)
   */
  domaine?: string | null;
  langue?: ('Anglais' | 'Français' | 'Arabe' | 'Autre') | null;
  tunisienEligible?: ('oui' | 'non' | 'inconnu') | null;
  statut?: ('active' | 'expiree' | 'a_venir') | null;
  niveau: string;
  description: string;
  eligibilite?: {
    nationalitesEligibles?: string | null;
    niveauRequis?: string | null;
    ageMax?: number | null;
    conditionsSpeciales?: string | null;
  };
  documentsRequis?:
    | {
        nom: string;
        obligatoire?: boolean | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  financement?: string | null;
  dateLimite?: string | null;
  dateOuverture?: string | null;
  lienOfficiel: string;
  /**
   * Logo ou image représentative de la bourse
   */
  image?: (string | null) | Media;
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidatures".
 */
export interface Candidature {
  id: string;
  user?: (string | null) | User;
  bourse_name: string;
  statut: 'en_attente' | 'examen' | 'acceptee' | 'refusee';
  date_depot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entretiens".
 */
export interface Entretien {
  id: string;
  user: string | User;
  score?: string | null;
  conversationId?: string | null;
  context?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bourses favorites par étudiant
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favoris".
 */
export interface Favoris {
  id: string;
  /**
   * Un seul document de favoris par utilisateur
   */
  user: string | User;
  userEmail?: string | null;
  bourses?:
    | {
        nom: string;
        pays?: string | null;
        lienOfficiel?: string | null;
        financement?: string | null;
        dateLimite?: string | null;
        ajouteLe?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap".
 */
export interface Roadmap {
  id: string;
  userId: string;
  userEmail?: string | null;
  nom: string;
  pays?: string | null;
  lienOfficiel?: string | null;
  financement?: string | null;
  dateLimite?: string | null;
  ajouteLe?: string | null;
  statut?: ('en_cours' | 'soumis' | 'accepte' | 'refuse') | null;
  etapeCourante?: number | null;
  notes?: string | null;
  etapes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  conseilGlobal?: string | null;
  langue?: string | null;
  deadlineFinale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: string;
  name: string;
  email: string;
  rating: number;
  comment: string;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Scores de compatibilité entre étudiants et bourses avec analyse détaillée
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match".
 */
export interface Match {
  id: string;
  /**
   * Étudiant
   */
  userId: string | User;
  /**
   * Bourse évaluée
   */
  bourseId: string | Bourse;
  /**
   * Score global de compatibilité (0-100)
   */
  matchScore: number;
  matchBreakdown: {
    /**
     * Score d'éligibilité (35% du total)
     */
    eligibility: number;
    /**
     * Score d'expérience académique & pro (35% du total)
     */
    experience: number;
    /**
     * Score de certifications & tests (25% du total)
     */
    certifications: number;
    /**
     * Bonus ou malus additif
     */
    bonus: number;
  };
  /**
   * L'étudiant dispose-t-il d'une certification de langue internationale ?
   */
  hasLanguageTest?: boolean | null;
  /**
   * Détails du test de langue si disponible
   */
  languageTestDetails?: {
    /**
     * Type de test
     */
    testType?: ('IELTS' | 'TOEFL' | 'DELF' | 'DALF' | 'TEF' | 'TCF') | null;
    /**
     * Score obtenu
     */
    score?: number | null;
    /**
     * Niveau (B1, B2, C1, C2, etc)
     */
    level?: string | null;
    /**
     * Date d'expiration du test
     */
    expiryDate?: string | null;
  };
  /**
   * Raisons du match
   */
  matchReasons?: string | null;
  /**
   * Conseils pour améliorer le score
   */
  recommendations?:
    | {
        category: 'language' | 'experience' | 'certification' | 'academic' | 'gpa' | 'research';
        /**
         * Conseil détaillé
         */
        text: string;
        /**
         * Points potentiels à gagner
         */
        impact: '5' | '10' | '15' | '20';
        priority: 'high' | 'medium' | 'low';
        id?: string | null;
      }[]
    | null;
  /**
   * Statut du score
   */
  statut: 'active' | 'archived' | 'pending';
  /**
   * Deadline de la bourse (copie depuis Bourses)
   */
  dateLimite: string;
  /**
   * Jours restants pour postuler (calculé)
   */
  jourcRestants?: number | null;
  /**
   * Détails académiques de l'étudiant au moment du scoring
   */
  academicDetails?: {
    /**
     * GPA/Moyenne au moment du scoring
     */
    gpa?: number | null;
    /**
     * Nombre de projets académiques
     */
    projectCount?: number | null;
    /**
     * Nombre de publications
     */
    publicationCount?: number | null;
    /**
     * A participé à la recherche
     */
    hasResearchExperience?: boolean | null;
  };
  /**
   * Détails professionnels au moment du scoring
   */
  professionalDetails?: {
    /**
     * Mois d'expérience professionnelle
     */
    workExperienceMonths?: number | null;
    /**
     * A complété un stage
     */
    hasInternship?: boolean | null;
    /**
     * A une responsabilité de leadership
     */
    hasLeadershipRole?: boolean | null;
    /**
     * Nombre de certifications professionnelles
     */
    certificationCount?: number | null;
  };
  /**
   * Détails de la bourse au moment du scoring (snapshot)
   */
  scholarshipDetails?: {
    bourseNom?: string | null;
    boursePays?: string | null;
    bourseDomaine?: string | null;
    bourseNiveau?: string | null;
    bourseStatut?: string | null;
    tunisienEligible?: string | null;
  };
  /**
   * Version de l'algorithme utilisé
   */
  algorithmVersion?: string | null;
  /**
   * Quand le score a été calculé
   */
  calculatedAt: string;
  /**
   * Notes internes (non visibles à l'étudiant)
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations".
 */
export interface Recommendation {
  id: string;
  /**
   * L'étudiant pour lequel les recommandations sont générées
   */
  studentProfile: string | User;
  scholarships: {
    bourseId: string;
    titre: string;
    description?: string | null;
    domaine?: string | null;
    niveau?: string | null;
    pays?: string | null;
    montant?: string | null;
    deadline?: string | null;
    lien?: string | null;
    score: number;
    raisons?:
      | {
          raison?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Score maximum de la meilleure recommandation
   */
  scoreMax: number;
  /**
   * Date et heure de génération des recommandations
   */
  dateGeneration: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'bourses';
        value: string | Bourse;
      } | null)
    | ({
        relationTo: 'candidatures';
        value: string | Candidature;
      } | null)
    | ({
        relationTo: 'entretiens';
        value: string | Entretien;
      } | null)
    | ({
        relationTo: 'favoris';
        value: string | Favoris;
      } | null)
    | ({
        relationTo: 'roadmap';
        value: string | Roadmap;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'match';
        value: string | Match;
      } | null)
    | ({
        relationTo: 'recommendations';
        value: string | Recommendation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  pays?: T;
  niveau?: T;
  domaine?: T;
  phone?: T;
  nationality?: T;
  countryOfResidence?: T;
  linkedin?: T;
  github?: T;
  portfolio?: T;
  currentLevel?: T;
  fieldOfStudy?: T;
  institution?: T;
  gpa?: T;
  graduationYear?: T;
  targetDegree?: T;
  motivationSummary?: T;
  academicHistory?:
    | T
    | {
        degree?: T;
        institution?: T;
        field?: T;
        year?: T;
        grade?: T;
        id?: T;
      };
  workExperience?:
    | T
    | {
        type?: T;
        position?: T;
        company?: T;
        city?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        technologies?: T;
        id?: T;
      };
  academicProjects?:
    | T
    | {
        title?: T;
        type?: T;
        supervisor?: T;
        year?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        technologies?: T;
        link?: T;
        teamSize?: T;
        impact?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        date?: T;
        credential?: T;
        id?: T;
      };
  volunteerWork?:
    | T
    | {
        role?: T;
        organization?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        id?: T;
      };
  publications?:
    | T
    | {
        title?: T;
        venue?: T;
        year?: T;
        authors?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        title?: T;
        organization?: T;
        year?: T;
        description?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        certificate?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        skill?: T;
        level?: T;
        category?: T;
        id?: T;
      };
  targetCountries?:
    | T
    | {
        country?: T;
        id?: T;
      };
  targetFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  progression?:
    | T
    | {
        bourseNom?: T;
        etape?: T;
        updatedAt?: T;
        id?: T;
      };
  magicToken?: T;
  magicTokenExpiration?: T;
  bourses_choisies?:
    | T
    | {
        nom?: T;
        pays?: T;
        url?: T;
        deadline?: T;
        langue?: T;
        ajouteLe?: T;
        id?: T;
      };
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  text?: T;
  role?: T;
  conversationId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bourses_select".
 */
export interface BoursesSelect<T extends boolean = true> {
  nom?: T;
  pays?: T;
  domaine?: T;
  langue?: T;
  tunisienEligible?: T;
  statut?: T;
  niveau?: T;
  description?: T;
  eligibilite?:
    | T
    | {
        nationalitesEligibles?: T;
        niveauRequis?: T;
        ageMax?: T;
        conditionsSpeciales?: T;
      };
  documentsRequis?:
    | T
    | {
        nom?: T;
        obligatoire?: T;
        description?: T;
        id?: T;
      };
  financement?: T;
  dateLimite?: T;
  dateOuverture?: T;
  lienOfficiel?: T;
  image?: T;
  embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidatures_select".
 */
export interface CandidaturesSelect<T extends boolean = true> {
  user?: T;
  bourse_name?: T;
  statut?: T;
  date_depot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entretiens_select".
 */
export interface EntretiensSelect<T extends boolean = true> {
  user?: T;
  score?: T;
  conversationId?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favoris_select".
 */
export interface FavorisSelect<T extends boolean = true> {
  user?: T;
  userEmail?: T;
  bourses?:
    | T
    | {
        nom?: T;
        pays?: T;
        lienOfficiel?: T;
        financement?: T;
        dateLimite?: T;
        ajouteLe?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap_select".
 */
export interface RoadmapSelect<T extends boolean = true> {
  userId?: T;
  userEmail?: T;
  nom?: T;
  pays?: T;
  lienOfficiel?: T;
  financement?: T;
  dateLimite?: T;
  ajouteLe?: T;
  statut?: T;
  etapeCourante?: T;
  notes?: T;
  etapes?: T;
  conseilGlobal?: T;
  langue?: T;
  deadlineFinale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  rating?: T;
  comment?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match_select".
 */
export interface MatchSelect<T extends boolean = true> {
  userId?: T;
  bourseId?: T;
  matchScore?: T;
  matchBreakdown?:
    | T
    | {
        eligibility?: T;
        experience?: T;
        certifications?: T;
        bonus?: T;
      };
  hasLanguageTest?: T;
  languageTestDetails?:
    | T
    | {
        testType?: T;
        score?: T;
        level?: T;
        expiryDate?: T;
      };
  matchReasons?: T;
  recommendations?:
    | T
    | {
        category?: T;
        text?: T;
        impact?: T;
        priority?: T;
        id?: T;
      };
  statut?: T;
  dateLimite?: T;
  jourcRestants?: T;
  academicDetails?:
    | T
    | {
        gpa?: T;
        projectCount?: T;
        publicationCount?: T;
        hasResearchExperience?: T;
      };
  professionalDetails?:
    | T
    | {
        workExperienceMonths?: T;
        hasInternship?: T;
        hasLeadershipRole?: T;
        certificationCount?: T;
      };
  scholarshipDetails?:
    | T
    | {
        bourseNom?: T;
        boursePays?: T;
        bourseDomaine?: T;
        bourseNiveau?: T;
        bourseStatut?: T;
        tunisienEligible?: T;
      };
  algorithmVersion?: T;
  calculatedAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations_select".
 */
export interface RecommendationsSelect<T extends boolean = true> {
  studentProfile?: T;
  scholarships?:
    | T
    | {
        bourseId?: T;
        titre?: T;
        description?: T;
        domaine?: T;
        niveau?: T;
        pays?: T;
        montant?: T;
        deadline?: T;
        lien?: T;
        score?: T;
        raisons?:
          | T
          | {
              raison?: T;
              id?: T;
            };
        id?: T;
      };
  scoreMax?: T;
  dateGeneration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}