/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    messages: Message;
    bourses: Bourse;
    candidatures: Candidature;
    entretiens: Entretien;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    bourses: BoursesSelect<false> | BoursesSelect<true>;
    candidatures: CandidaturesSelect<false> | CandidaturesSelect<true>;
    entretiens: EntretiensSelect<false> | EntretiensSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  pays?: string | null;
  niveau?: string | null;
  domaine?: string | null;
  phone?: string | null;
  nationality?: string | null;
  countryOfResidence?: string | null;
  currentLevel?: string | null;
  fieldOfStudy?: string | null;
  institution?: string | null;
  gpa?: string | null;
  graduationYear?: string | null;
  targetDegree?: string | null;
  motivationSummary?: string | null;
  academicHistory?:
    | {
        degree?: string | null;
        institution?: string | null;
        field?: string | null;
        year?: string | null;
        grade?: string | null;
        id?: string | null;
      }[]
    | null;
  workExperience?:
    | {
        type?: string | null;
        position?: string | null;
        company?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language?: string | null;
        level?: string | null;
        certificate?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        skill?: string | null;
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  targetCountries?:
    | {
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  targetFields?:
    | {
        field?: string | null;
        id?: string | null;
      }[]
    | null;
  progression?:
    | {
        bourseNom?: string | null;
        etape?: number | null;
        updatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  magicToken?: string | null;
  magicTokenExpiration?: string | null;
  bourses_choisies?:
    | {
        nom: string;
        pays?: string | null;
        url?: string | null;
        deadline?: string | null;
        langue?: string | null;
        ajouteLe?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Texte alternatif pour l'accessibilité
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  text: string;
  role: 'user' | 'assistant';
  conversationId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bourses".
 */
export interface Bourse {
  id: string;
  nom: string;
  pays: string;
  domaine?:
    | (
        | 'Sciences'
        | 'Ingénierie'
        | 'Médecine'
        | 'Droit'
        | 'Économie'
        | 'Arts'
        | 'Informatique'
        | 'Agriculture'
        | 'Tous domaines'
      )
    | null;
  langue?: ('Anglais' | 'Français' | 'Arabe' | 'Autre') | null;
  tunisienEligible?: ('oui' | 'non' | 'inconnu') | null;
  statut?: ('active' | 'expiree' | 'a_venir') | null;
  niveau: string;
  description: string;
  financement?: string | null;
  dateLimite?: string | null;
  dateOuverture?: string | null;
  lienOfficiel: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidatures".
 */
export interface Candidature {
  id: string;
  user?: (string | null) | User;
  bourse_name: string;
  statut: 'en_attente' | 'examen' | 'acceptee' | 'refusee';
  date_depot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entretiens".
 */
export interface Entretien {
  id: string;
  user: string | User;
  score?: string | null;
  conversationId?: string | null;
  context?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'bourses';
        value: string | Bourse;
      } | null)
    | ({
        relationTo: 'candidatures';
        value: string | Candidature;
      } | null)
    | ({
        relationTo: 'entretiens';
        value: string | Entretien;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  pays?: T;
  niveau?: T;
  domaine?: T;
  phone?: T;
  nationality?: T;
  countryOfResidence?: T;
  currentLevel?: T;
  fieldOfStudy?: T;
  institution?: T;
  gpa?: T;
  graduationYear?: T;
  targetDegree?: T;
  motivationSummary?: T;
  academicHistory?:
    | T
    | {
        degree?: T;
        institution?: T;
        field?: T;
        year?: T;
        grade?: T;
        id?: T;
      };
  workExperience?:
    | T
    | {
        type?: T;
        position?: T;
        company?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        certificate?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        skill?: T;
        level?: T;
        id?: T;
      };
  targetCountries?:
    | T
    | {
        country?: T;
        id?: T;
      };
  targetFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  progression?:
    | T
    | {
        bourseNom?: T;
        etape?: T;
        updatedAt?: T;
        id?: T;
      };
  magicToken?: T;
  magicTokenExpiration?: T;
  bourses_choisies?:
    | T
    | {
        nom?: T;
        pays?: T;
        url?: T;
        deadline?: T;
        langue?: T;
        ajouteLe?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  text?: T;
  role?: T;
  conversationId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bourses_select".
 */
export interface BoursesSelect<T extends boolean = true> {
  nom?: T;
  pays?: T;
  domaine?: T;
  langue?: T;
  tunisienEligible?: T;
  statut?: T;
  niveau?: T;
  description?: T;
  financement?: T;
  dateLimite?: T;
  dateOuverture?: T;
  lienOfficiel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidatures_select".
 */
export interface CandidaturesSelect<T extends boolean = true> {
  user?: T;
  bourse_name?: T;
  statut?: T;
  date_depot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entretiens_select".
 */
export interface EntretiensSelect<T extends boolean = true> {
  user?: T;
  score?: T;
  conversationId?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}